spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_db
    username: demo
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    drop-first: true
    default-schema: public
    change-log: classpath:db.changelog/changelog-master.yml